#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

if npm run lint && make test;
then
    exit 0
else
    echo "\\e[1;33m One or more tests are failing; please fix those tests before commiting"
    exit 1
fi